import { League_Spartan as LeagueSpartan } from 'next/font/google'
import './globals.css'

const spartan = LeagueSpartan({
  subsets: ['latin'],
  variable: ['--font-spartan'],
  weight: ['400', '500', '700'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spartan.variable} font-spartan`}>{children}</body>
    </html>
  )
}
